Repository startupjs/startupjs, pull requests merged in 2020-12, with the labels that each got.

#415 fix(ui -> Popover): visible true
  packages/ui/components/popups/Popover/index.js
Labels: bug

#397 ref(Modal): refactor Modal, use RNModal for web
  docs/migration-guides/0.29.md
  docs/migration-guides/0.30.md
  packages/auth-azuread/client/components/AuthButton/index.js
  packages/auth-linkedin/client/components/AuthButton/index.js
  packages/docs/client/app/Layout/Sidebar/Content/Options/index.js
  packages/docs/client/components/Props/Renderer/index.js
  packages/ui/components/Modal/Modal.en.mdx
  packages/ui/components/Modal/Modal.ru.mdx
  packages/ui/components/Modal/ModalActions/index.js
  packages/ui/components/Modal/ModalHeader/index.js
  packages/ui/components/Modal/index.js
  packages/ui/components/Modal/index.styl
  packages/ui/components/Modal/layout.js
  packages/ui/components/Modal/modal.js
  packages/ui/components/Modal/modal.web.js
  packages/ui/components/popups/Drawer/index.js
  packages/ui/components/popups/Popover/index.js
Labels: WIP, breaking change

#434 ci(e2e): Implement detox
  .eslintrc.json
  package.json
  packages/docs/client/app/Layout/Sidebar/Content/index.js
  packages/docs/client/app/Layout/index.js
  styleguide/.detoxrc.json
  styleguide/.gitignore
  styleguide/config.json
  styleguide/e2e/config.json
  styleguide/e2e/environment.js
  styleguide/e2e/firstTest.e2e.js
  styleguide/e2e/helpers.js
  styleguide/e2e/init.js
  styleguide/ios/Podfile.lock
  styleguide/ios/styleguide.xcodeproj/project.pbxproj
  styleguide/package.json
  yarn.lock
Labels: WIP
